### PR TITLE
feat: Better VTT and SRT

### PR DESCRIPTION
**Pull request by lukeocodes**
- doesn't include diarize
- doesn't do paragraphs
- requires utterances

### CODE REVIEW

**Comment by lukeocodes** [comment]
the timestamps are a whole hour out

**Comment by lukeocodes** [comment]
Needed `.utc()` instead of `.tz('UTC')`

**Comment by lukeocodes** [comment]
Discord context: https://discord.com/channels/1108042150941294664/1108042151964725311/1119157678481100870

image

**Comment by lukeocodes** [comment]
New sample output meets standards and formatting for official WebVTTs, including those set by the BBC.

VTT output for https://dpgr.am/spacewalk.wav

```
WEBVTT
  
  NOTE
  Transcription provided by Deepgram
  Request Id: c64b8ec6-4397-4ab8-82b8-63801944417a
  Created: 2023-06-20T15:04:07.532Z
  Duration: 169.802
  Channels: 1
  
  01:00:03.199 --> 01:00:04.019
  and jessica
  
  01:00:05.359 --> 01:00:07.585
  christina we are so proud of you
  
  01:00:08.545 --> 01:00:10.385
  you're gonna do great today we'll be waiting
  
  01:00:10.385 --> 01:00:11.585
  for you here in a couple of hours
  
  01:00:11.585 --> 01:00:13.424
  when you get home i'm gonna hand you
  
  01:00:13.424 --> 01:00:14.725
  over to stephanie now
  
  01:00:15.740 --> 01:00:18.380
  have a great great eva drew thank you
  
  01:00:18.380 --> 01:00:20.460
  so much and our pleasure working with you
  
  01:00:20.460 --> 01:00:22.060
  this morning and what can i get in
  
  01:00:22.060 --> 01:00:23.280
  that ev hatch open
  
  01:00:23.675 --> 01:00:24.655
  and i could import
  
  01:00:25.675 --> 01:00:27.055
  it's opened and stowed
  
  01:00:28.875 --> 01:00:31.215
  thank you drew thank you so much
  
  01:00:31.720 --> 01:00:32.220
  jessica
  
  01:00:38.280 --> 01:00:39.100
  on your dcms
  
  01:00:39.715 --> 01:00:42.275
  take your power switches to bat stagger switch
  
  01:00:42.275 --> 01:00:43.975
  throws and expect a warning tone
  
  01:01:04.220 --> 01:01:05.979
  final steps before they begin the space lock
  
  01:01:06.060 --> 01:01:08.080
  copy check display switch functional
  
  01:01:14.075 --> 01:01:15.935
  tracy how important is this this
  
  01:01:16.715 --> 01:01:18.479
  by guiding it through is seems like seems
  
  01:01:18.479 --> 01:01:20.000
  like a lot to remember on your own
  
  01:01:20.000 --> 01:01:20.500
  absolutely
  
  01:01:21.759 --> 01:01:23.939
  take power e b 1 e b 2
  
  01:01:24.080 --> 01:01:26.560
  2 switches to off o f f yeah
  
  01:01:26.560 --> 01:01:29.585
  christina and jessica have enough work with their
  
  01:01:29.585 --> 01:01:31.825
  hands and feet and their brain outside that
  
  01:01:31.825 --> 01:01:33.865
  it really helps to have someone like stephanie
  
  01:01:34.145 --> 01:01:35.525
  do power both off
  
  01:01:50.455 --> 01:01:53.200
  dcms this connect your scus from your dcms
  
  01:01:53.340 --> 01:01:55.280
  and stow the scus in the pouch
  
  01:01:58.395 --> 01:02:01.215
  commentator of so not only does stephanie
  
  01:02:22.480 --> 01:02:24.720
  38 am cst a little ahead of schedule
  
  01:02:24.720 --> 01:02:27.735
  about 12 minutes but that gets us started
  
  01:02:27.735 --> 01:02:29.595
  on today's historic space walk
  
  01:02:34.150 --> 01:02:36.890
  andrew morgan there wishing the crew luck simulated
  
  01:02:36.950 --> 01:02:38.970
  in pouch and dcm cover close
  
  01:02:42.685 --> 01:02:43.825
  copy ev 2
```

**Review by briancbarrow — APPROVED** [review]

**Pull request merged**
